p8105_hw3_yx2954
================
Yiran Xu
2024-10-10

``` r
library(p8105.datasets)
library(dplyr)
```

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

``` r
library(lubridate)
```

    ## 
    ## Attaching package: 'lubridate'

    ## The following objects are masked from 'package:base':
    ## 
    ##     date, intersect, setdiff, union

``` r
library(ggplot2)
library(ggridges)
library(readr)
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ forcats 1.0.0     ✔ tibble  3.2.1
    ## ✔ purrr   1.0.2     ✔ tidyr   1.3.1
    ## ✔ stringr 1.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
knitr::opts_chunk$set(fig.path = "data/plots/")
```

# Problem 1

## First, let’s take a few minutes to understand the dataset and the variables it contains.

``` r
str(ny_noaa)
```

    ## tibble [2,595,176 × 7] (S3: tbl_df/tbl/data.frame)
    ##  $ id  : chr [1:2595176] "US1NYAB0001" "US1NYAB0001" "US1NYAB0001" "US1NYAB0001" ...
    ##  $ date: Date[1:2595176], format: "2007-11-01" "2007-11-02" ...
    ##  $ prcp: int [1:2595176] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ snow: int [1:2595176] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ snwd: int [1:2595176] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ tmax: chr [1:2595176] NA NA NA NA ...
    ##  $ tmin: chr [1:2595176] NA NA NA NA ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   id = col_character(),
    ##   ..   date = col_date(format = ""),
    ##   ..   prcp = col_integer(),
    ##   ..   snow = col_integer(),
    ##   ..   snwd = col_integer(),
    ##   ..   tmax = col_character(),
    ##   ..   tmin = col_character()
    ##   .. )

``` r
nrow(ny_noaa)
```

    ## [1] 2595176

``` r
ncol(ny_noaa)
```

    ## [1] 7

``` r
n_station = 
  ny_noaa |>
  pull(id) |>
  n_distinct()

date_range = ny_noaa |>
  pull(date) |>
  range(na.rm = TRUE)
```

## Next, check the range of key variables

### prcp

``` r
max_prcp_info = ny_noaa |>
  filter(prcp == max(prcp, na.rm = TRUE)) |>
  select(id, date, prcp)

min_prcp_info = ny_noaa |>
  filter(prcp == min(prcp, na.rm = TRUE)) |>
  select(id, date, prcp)
```

### snow & snwd

``` r
max_snow_info = ny_noaa |>
  filter(snow == max(snow, na.rm = TRUE)) |>
  select(id, date, snow)

min_snow_info = ny_noaa |>
  filter(snow == min(snow, na.rm = TRUE)) |>
  select(id, date, snow)

max_snwd_info = ny_noaa |>
  filter(snwd == max(snwd, na.rm = TRUE)) |>
  select(id, date, snwd)

min_snwd_info = ny_noaa |>
  filter(snwd == min(snwd, na.rm = TRUE)) |>
  select(id, date, snwd)
```

### tmax & tmin

``` r
max_tmax_info = ny_noaa |>
  mutate(tmax = as.numeric(tmax)) |>
  filter(tmax == max(tmax, na.rm = TRUE)) |>
  select(id, date, tmax, tmin)

min_tmax_info = ny_noaa |>
  mutate(tmax = as.numeric(tmax)) |>
  filter(tmax == min(tmax, na.rm = TRUE)) |>
  select(id, date, tmax, tmin)

max_tmin_info = ny_noaa |>
  mutate(tmin = as.numeric(tmin)) |>
  filter(tmin == max(tmin, na.rm = TRUE)) |>
  select(id, date, tmin)

min_tmin_info = ny_noaa |>
  mutate(tmin = as.numeric(tmin)) |>
  filter(tmin == min(tmin, na.rm = TRUE)) |>
  select(id, date, tmin)
```

## Then, count missing info

``` r
na_snow = ny_noaa |>
  filter(is.na(snow)) |>
  count() 

na_snwd = ny_noaa |>
  filter(is.na(snwd)) |>
  count()

na_tmax = ny_noaa |>
  filter(is.na(tmax)) |>
  count()

na_tmin = ny_noaa |>
  filter(is.na(tmin)) |>
  count()
```

## Description

- The table size is **2595176** by **7**. Variables includes **id** (the
  identifier for specific weather station), **date**,
  **prcp(precipitation)**, **snow(snowfall)**, **snwd(snow depth in
  millimeters)**, **maximum and minimun temperature**.
- This table contains data from **747** distinct stations in total from
  **1981-01-01** to **2010-12-31**.
- The maximum precipitation was **22860** observed on **1982-08-20** at
  **USC00306839**. The minimum is **0**, as expected. There were
  **1471511** days without raning.
- The maximum snowfall was **10160** on **1983-04-11** at
  **USC00309516**, while the minimum was **-13** on **2005-06-15** at
  **USC00307400**. An recording error may occur on that day as the
  snowfall cannot be negative.
- The maximum snow depth was **9195** observed on **1989-02-19** at
  **USC00308248**. The minimum is **0** as expected. There were
  **1621683** days without snow accumulation.
- The maximum tmax was **600** observed on **34** different days. The
  minimum was **-389** observed on **1995-02-07** at **USC00306184**.
- The maximum tmin was **600** on **30** different days. The minimum was
  **-594** on **2004-12-20** at **USR0000NSCH**
- There is a high degree of missing information in the table. For snow
  and snwd, about **14.69%** and **22.8%** are missing information,
  respectively. **43.71%** and **43.71%** of max and min temperature are
  missing.

## data cleaning

- Clean name;
- Convert tmax and tmin to numeric data;
- Keep temperature, precipitation, snowfall in reasonable units
- Create seperate columns for year, month and day
- Remove error, i.e. tmax \<= tmin; snow \< 0;
- Remove empty row

``` r
ny_noaa_clean = ny_noaa |>
  janitor::clean_names() |>
  mutate(tmax = as.numeric(tmax) / 10, 
         tmin = as.numeric(tmin) / 10,
         prcp = prcp / 10,
         year = year(date),
         month = month(date),
         day = day(date)) |> 
  select(year, month, day, everything(), -date) |>
  filter(tmax > tmin | is.na(tmax) | is.na(tmin)) |>
  filter(snow >= 0 | is.na(snow)) |>
  filter(!(is.na(snow) & is.na(snwd) & is.na(tmax) & is.na(tmin) & is.na(prcp))) |>
  rename(
    tmax_c = tmax,     
    tmin_c = tmin,     
    prcp_mm = prcp,   
    snow_mm = snow,    
    snwd_mm = snwd     
  )
```

## Count most common snowfall

``` r
ny_noaa_clean |> 
  count(snow_mm) |>
  arrange(desc(n)) 
```

    ## # A tibble: 281 × 2
    ##    snow_mm       n
    ##      <int>   <int>
    ##  1       0 2007240
    ##  2      NA  308654
    ##  3      25   30981
    ##  4      13   23082
    ##  5      51   18253
    ##  6      76   10159
    ##  7       8    9959
    ##  8       5    9742
    ##  9      38    9186
    ## 10       3    8786
    ## # ℹ 271 more rows

For snowfall, the most commonly observed values is 0mm among with
2007240 observations, as there is no snow in most of the days.

## make two-panel plot

### filter and group data

``` r
avg_tmax_df = 
  ny_noaa_clean |>
  filter(month %in% c(1, 7) & !is.na(tmax_c)) |>
  group_by(id, month) |>
  summarise(avg_tmax = mean(tmax_c))
```

    ## `summarise()` has grouped output by 'id'. You can override using the `.groups`
    ## argument.

### make plot

``` r
avg_tmax_p = ggplot(avg_tmax_df, aes(y = avg_tmax, fill = factor(month, labels = c("January", "July")))) +
  geom_boxplot() +  
  facet_grid(.~ month, labeller = labeller(month = c(`1` = "January", `7` = "July"))) +
  labs(title = "Average Max Temperature in January and July by Station",
       x = "Station",
       y = "Average Max Temperature (°C)",
       fill = "Month") +
  theme(axis.text.x = element_blank()) 

avg_tmax_p
```

![](data/plots/avg_tmax_plot-1.png)<!-- -->

``` r
#ggsave(filename = "data/plots/avg_tmax.png", avg_tmax_p)
```

It can be noticed that the average max temperature in January is greatly
lower than that in July. Outliers in both panel can be detected. The
average temperature in some station significantly higher or lower than
the mean.

## make other plots

### geom_hex

``` r
hex_p = ggplot(ny_noaa_clean, aes(x = tmin_c, y = tmax_c)) + 
  geom_hex() + 
  labs(x = "t_min (°C)",
       y = "t_max (°C)")

hex_p
```

    ## Warning: Removed 1063998 rows containing non-finite outside the scale range
    ## (`stat_binhex()`).

![](data/plots/hex_p-1.png)<!-- -->

``` r
#ggsave(filename = "data/plots/tmax_tmin.png", hex_p)
```

### Ridge plot

``` r
ridge_p = ny_noaa_clean |>
  filter(snow_mm > 0 & snow_mm< 100) |>
  ggplot(aes(x = snow_mm, y = as.factor(year))) + 
  geom_density_ridges() +
  labs(
    x = "Snowfall (mm)",
    y = "Frequency",
    title = "Distribution of Snowfall Values Greater Than 0 and Less Than 100 by Year"
  ) +
  scale_y_discrete(expand = expansion(add = c(1, 2)))

ridge_p
```

    ## Picking joint bandwidth of 3.76

![](data/plots/ridge_p-1.png)<!-- -->

``` r
#ggsave(filename = "data/plots/snow_dist.png", ridge_p)
```

# Problem 2

## load data

``` r
demo_df = read_csv("data/nhanes_covar.csv", na = c("NA", ".", ""), skip = 4) |>
  janitor::clean_names() 
```

    ## Rows: 250 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (5): SEQN, sex, age, BMI, education
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
acc_df = read_csv("data/nhanes_accel.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() 
```

    ## Rows: 250 Columns: 1441
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (1441): SEQN, min1, min2, min3, min4, min5, min6, min7, min8, min9, min1...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## merge df

``` r
anti_join(demo_df, acc_df, by = "seqn")
```

    ## # A tibble: 0 × 5
    ## # ℹ 5 variables: seqn <dbl>, sex <dbl>, age <dbl>, bmi <dbl>, education <dbl>

``` r
merged_df = left_join(demo_df, acc_df, by = "seqn")
```

## tidy & orgnize df

``` r
final_df = 
  merged_df |> 
  pivot_longer(cols = starts_with("min"),
               names_to = "minute",
               values_to = "acc") |>
  filter(age >= 21) |>
  drop_na(sex, age, bmi, education) |>
  mutate(
    sex = recode(sex, "1" = "Male", "2" = "Female"),
    education = recode(education, "1" = "Less than High School", "2" = "High School Equivalent", "3" = "More than High School"),
    sex = as_factor(sex), 
    education = fct_relevel(education, "Less than High School", "High School Equivalent", "More than High School"))
```

## reader-friendly table for the number of men and women in each education category

``` r
sex_edu = final_df |>
  group_by(sex, education) |>
  count()
```

## Visualization - age distribution

``` r
age_dist_p = final_df |>
  ggplot(aes(x = sex, y = age)) + 
  geom_violin(aes(fill = sex), alpha = .5) + 
  stat_summary(fun = "median", color = "blue") +
  facet_grid(. ~ education)

age_dist_p
```

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_segment()`).
    ## Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_segment()`).
    ## Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_segment()`).

![](data/plots/age_dist_p-1.png)<!-- -->

``` r
#ggsave("data/plots/age_dist.png", age_dist_p)
```

## Comments:

- Within male group, the number of people with more than high school
  education background is more than those with high school equivalent,
  while the number of those with less than high school education
  background is the least. The numbers are **80640**, **50400**, and
  **38880**, respectively.
- Within the female group, the number of those with high school
  equivalent education background is the least, followed by those with
  less than high school, and more than high school education background.
  The numbers are **33120**, **40320**, and **84960**, respectively.
- Comparing the male group and the female group, there are more males
  with high school equivalent background; however, there are more
  females with less than high school and more than high school
  background.
- The age distribution across different education background is shown in
  the picture. In Less than High School group, more males are
  concentrated on the age of 45 and 70-80, while above 70 are the most
  common age for female. The median age in female group is slightly
  higher than the median in male group.
- In High School Equivalent group, more males are concentrated on the
  age of 20-35 and 50-70, while 60-80 are the most common age for
  female. The median age in female group is higher than the median in
  male group.
- In More than High School group, the age distribution is relatively
  even, while 25-35 are the most common age for female, which is greatly
  different to the previous two groups. The median age in female group
  is slightly lower than the median in male group.

## Total activity vs age

### Get total activity

``` r
sum_acc = 
  final_df |>
  group_by(seqn) |>
  summarize(total_acc = sum(acc, na.rm = TRUE)) |>
  left_join(final_df %>% distinct(seqn, age, sex, education), by = 'seqn')
```

### Make plot

``` r
acc_age = ggplot(sum_acc, aes(x = age, y = total_acc, color = sex)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ education) +
  labs(title = "Total Activity vs Age by Gender and Education Level", x = "Age", y = "Total Activity") +
  theme_minimal()

acc_age
```

    ## `geom_smooth()` using method = 'loess' and formula = 'y ~ x'

![](data/plots/acc_age-1.png)<!-- -->

``` r
#ggsave("data/plots/acc_age.png", acc_age)
```

### Comments

- Although the points have a scattered distribution, it can be noticed
  that total activity decreases as age increases in general in all three
  groups.
- **Within Group**: Female with less than a high school background were
  more active overall than men, the opposite of the other two groups.
- **Across group**: Compared across groups, both male and female aged
  20 - 40 in more than high school group are less active than their
  peers in other groups, presumably because a higher proportion of these
  people working on office.
- Outliers can be detected in both High School Equivalent group and
  Higher than High School, with either apparently higher or lower total
  activity compare to others within the groups.

## acc VS mins

### Get acc distribution among t

``` r
acc_t_df = 
  final_df |>
  group_by(minute, sex, education) |>
  summarize(avg_acc_t = mean(acc, na.rm = TRUE)) |>
  mutate(minute = as.numeric(gsub("min", "", minute)))
```

    ## `summarise()` has grouped output by 'minute', 'sex'. You can override using the
    ## `.groups` argument.

### Make plot

``` r
acc_min = ggplot(acc_t_df, aes(x = minute, y = avg_acc_t, color = sex, education)) +
  geom_point(alpha = .2) +
  geom_smooth(aes(color = sex), se = FALSE) +
  facet_grid(education ~ .) +
  labs(title = "Average Activity vs Time by Gender and Education Level", x = "Minutes", y = "Average Activity") +
  theme(
    strip.text = element_text(size = 7)   
  )

acc_min
```

    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

![](data/plots/acc_min-1.png)<!-- -->

``` r
#ggsave("data/plots/acc_min.png", acc_min)
```

### Comments

- **General:** Across all education levels, participants exhibit a
  similar pattern of activity throughout the day. The activity level
  gradually increases in the morning, peaks in the middle of the day,
  and then declines during the evening. This trend suggests that
  population follow a normal daily rhythm, and mostly go to bed at
  minute 0.
- **Female VS Male:** In all education levels, there is a slight
  difference between the activity patterns of males and females. In
  general, male is less active than female during daytime, and tend to
  stay up late in the evening. According to the smooth trend, female has
  a higher peak value than male during daytime.
- **Education level:** There is barely an impact from education level,
  but it appears that people with less than high school background tend
  to have a slightly higher peak during daytime.
